name: Daily Sync

on: 
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout files
    - run: patch -p 0 < keep_packages.patch
      name: Patch to keep generated files
    - name: Week Number
      id: week-number
      run: "echo \"::set-output name=week::$(date +%U)\""
    - name: Adjust Package Versions
      run: find . -name 'package.json' -and -path '*/packages/*' -maxdepth 3 -exec sed -i 's|\(.*"version"\): "\(.*\)",.*|\1: '"\"\2-canary-${{ steps.week-number.outputs.week }}\"|"  {} +
    - run: yarn install
    - run: DEBUG_PROJECT_CREATION=true ./packages/pwa-buildpack/bin/buildpack create-project tmp-to-delete --template "venia-concept" --name "tmp-to-delete" --author "Test Author<user@example.com>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "yarn" --install 0
      name: Create packages
    - name: Upload binary to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --include *.tgz
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}