name: Daily Sync
on: [push]
#on: 
#  schedule:
#    - cron: "4 20 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: pwd && ls -al && ls -al .github
    - name: GitHub Sync to Upstream Repository
      uses: ./.github/actions/sync-from-upstream
      with:
        upstream_repo: https://github.com/magento/pwa-studio.git
