name: Manual Package
on:
  create:
    tags:
      - manual-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout files
    - run: patch -p 0 < keep_packages.patch
      name: Patch to keep generated files
    - name: Week Number
      id: week-number
      run: "echo \"::set-output name=week::$(date +%U)\""
    - name: Year Number
      id: year-number
      run: "echo \"::set-output name=year::$(date +%Y)\""
    - name: Grab Tag Name
      run: echo ::set-env name=TAG::${GITHUB_REF#refs/*/}
    - name: Adjust Package Versions
      run: .github/bump-version.sh $TAG
    - name: Debug output
      run: git --no-pager diff
    - run: yarn install
    - run: mkdir -p $GITHUB_WORKSPACE/output/packages/pwa-create
    - run: DEBUG_PROJECT_CREATION=true ./packages/pwa-buildpack/bin/buildpack create-project ../tmp-to-delete --template "venia-concept" --name "pwa-studio-canary" --author "Test Author<user@example.com>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "yarn" --install 0
      name: Create packages
    - name: Retain package.json
      run: sed -e "s#file://$GITHUB_WORKSPACE/packages/#https://canary-packages.fooman.com/#g" $GITHUB_WORKSPACE/../tmp-to-delete/package.json > $GITHUB_WORKSPACE/output/packages/pwa-create/package-$TAG.json
    - name: Upload packages to S3 bucket
      uses: docker://schoenwaldnils/s3-sync-action:0.5.1
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: $GITHUB_WORKSPACE/output/packages
    - uses: actions/upload-artifact@v2
      with:
        name: package-${{ env.TAG }}.json
        path: $GITHUB_WORKSPACE/output/packages/pwa-create/
