name: Weekly Package
#on: [push]
on:
  schedule:
    - cron: "14 20 * * 0"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout files
#    - run: patch -p 0 < keep_packages.patch
#      name: Patch to keep generated files
    - name: Week Number
      id: week-number
      run: "echo \"::set-output name=week::$(date +%U)\""
    - name: Year Number
      id: year-number
      run: "echo \"::set-output name=year::$(date +%Y)\""
    - name: Adjust Package Versions
      run: .github/bump-version.sh ${{ steps.year-number.outputs.year }}-${{ steps.week-number.outputs.week }}
    - name: Debug output
      run: git --no-pager diff
    - run: cd $GITHUB_WORKSPACE && yarn install
    - run: mkdir -p $GITHUB_WORKSPACE/output/packages/pwa-create
    - run: DEBUG_PROJECT_CREATION=1 $GITHUB_WORKSPACE/packages/pwa-buildpack/bin/buildpack create-project $GITHUB_WORKSPACE/../tmp-to-delete --template "venia-concept" --name "pwa-studio-canary" --author "Test Author<user@example.com" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "yarn" --no-install
      name: Create packages
    - name: Copy packages to output folder
      run: cd $GITHUB_WORKSPACE && cp --parents ./packages/*/*.tgz $GITHUB_WORKSPACE/output && cp --parents ./packages/extensions/*/*.tgz $GITHUB_WORKSPACE/output
    - name: Retain package.json
      run: sed -e "s#file://$GITHUB_WORKSPACE/packages/#https://canary-packages.fooman.com/#g" $GITHUB_WORKSPACE/../tmp-to-delete/package.json > $GITHUB_WORKSPACE/output/packages/pwa-create/package-${{ steps.year-number.outputs.year }}-${{ steps.week-number.outputs.week }}.json
    - name: Upload packages to S3 bucket
      uses: docker://schoenwaldnils/s3-sync-action:0.5.1
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: $GITHUB_WORKSPACE/output/packages
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: fooman-canary-${{ steps.year-number.outputs.year }}-${{ steps.week-number.outputs.week }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: fooman-canary-${{ steps.year-number.outputs.year }}-${{ steps.week-number.outputs.week }}
        release_name: Release ${{ steps.year-number.outputs.year }}-${{ steps.week-number.outputs.week }}
        body: |
          [Latest package.json](https://canary-packages.fooman.com/pwa-create/package-${{ steps.year-number.outputs.year }}-${{ steps.week-number.outputs.week }}.json)
        prerelease: true
    - uses: actions/upload-artifact@v2
      with:
        name: package-${{ steps.year-number.outputs.year }}-${{ steps.week-number.outputs.week }}.json
        path: ${{ github.workspace }}/output/packages/pwa-create/
